### ISSUE TITLE
v5

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#450]
- [x] Target TypeScript 5.9
- [x] https://github.com/sindresorhus/type-fest/issues/1143
- [x] `ArrayTail`: Make `preserveReadonly` option true by default.
- [x] Move to ESM
- [x] Target Node.js 20
- [x] Make the `preserveConsecutiveUppercase` option in `CamelCase` `false` by default
- [x] Remove this: https://github.com/sindresorhus/type-fest/commit/32d94ddf02dba559655a9722bf8c481d4045e766#diff-9589c7ca28e78a91ac6a3982dce6a6be80734e70af0bcea4092ecaebc04190ffR1-R3
- [x] Make `PartialDeep` `allowUndefinedInNonTupleArrays` option `false` by default.
- [x] Make `Split` `strictLiteralChecks` option `true` by default.
- [x] https://github.com/sindresorhus/type-fest/pull/1029
- [x] https://github.com/sindresorhus/type-fest/pull/875
- [x] `Schema`: Remove `undefined` from `recurseIntoArrays` option.
- [x] Add a constraint of `object` to `T` for `WritableKeysOf` and `ReadonlyKeysOf`
- [x] Remove `strict: false` workaround: https://github.com/sindresorhus/type-fest/pull/1096
- [x] Move `ObservableLike` type to separate export since it mutates global: https://github.com/sindresorhus/type-fest/issues/1122#issuecomment-2858728080
- [x] Decide on If/Is types.

**Comment by voxpelli** [comment]
Possibly: https://github.com/sindresorhus/type-fest/issues/863

**Comment by sindresorhus** [comment]
@som-sm @Emiyaaaaa I'm planning v5 for right after TypeScript 5.9 is out. Probably 2-3 months out.

Please discuss here if there are any other breaking changes we should do that are not mentioned in the issue body.

**Comment by som-sm** [comment]
@sindresorhus Do we want to update anything with the `If*` types, as suggested in https://github.com/sindresorhus/type-fest/issues/788#issuecomment-2408420468?

<br>

> I would deprecate the Is* and refer people to the If* (https://github.com/sindresorhus/type-fest/issues/788#issuecomment-2411093782)

I feel more inclined towards this, but `Is*` variants are likely much more common in codebases, so deprecating them could be annoying.

**Comment by filipw01** [comment]
Linking it to update behavior of `kebabCase` https://github.com/sindresorhus/type-fest/issues/1074#issuecomment-2698729943

**Comment by som-sm** [comment]
Cool @sindresorhus, I'll start creating PRs for the tasks listed here.

**Comment by sindresorhus** [comment]
> Align behavior with Lodash: https://github.com/sindresorhus/type-fest/issues/1074#issuecomment-2698729943

@som-sm Do we still want to do this?

**Comment by som-sm** [comment]
> [@som-sm](https://github.com/som-sm) Do we still want to do this?

I think we can skip this for now, it'll require a proper rewrite, we can move it to v6.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/type-fest/releases/tag/v5.0.0
